language: ruby
rvm:
    - 2.2

sudo: false
 
script:
    - bundle exec rake
   
before_install:
    - gem update --system
    - gem --version
    
    
deploy:
    provider: heroku
    api_key:
        secure: 30c46bcd-7d7c-4db1-baff-a0b753fe209f