language: ruby
rvm:
    - 2.2

sudo: false
 
script:
    - bundle exec rake
   
before_install:
    - gem update --system
    - gem --version
    
deploy:
    provider: heroku
    api_key:
        secure: a3bce854-c6c0-4446-a05d-981cd2c348e1
    app: jubilatorpro
    run:
        - "rake db:create:all"
        - "rake db:migrate"
        - "rake db:setup"

services:
  - postgresql
  
  
before_script:
  - psql -c 'create database test_app;' -U postgres